# for titanicweb image
FROM php:7.2-apache
MAINTAINER Harvash <harvash2004@yahoo.com>

RUN apt-get update

# Install Postgre PDO
RUN apt-get install -y libpq-dev \
    && docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql \
    && docker-php-ext-install pdo pdo_pgsql pgsql