version: '3.5'

services:
  postgres:
    container_name: db_postgres
    image: pgtitanic:latest

    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /pgdb/data
      POSTGRES_DB: titanicdb
      
    volumes:
      - pgdata:/pgdb/data
      - pglogs:/pgdb/logs
      - ./pgdb/scripts:/pgdb/scripts
      - ./provision/:/docker-entrypoint-initdb.d/
      
    command: >
      postgres -c logging_collector=on 
      -c log_destination=stderr 
      -c log_directory=/pgdb/logs 
      -c log_filename=postgresql.log 
      -c log_file_mode=0600 
      -c log_truncate_on_rotation=on 
      -c log_rotation_age=1d 
      -c log_rotation_size=10MB  
      -c shared_preload_libraries='pg_stat_statements'
      
    ports:
      - "5432:5432"
    networks:
      titanicnet:
        ipv4_address: 10.10.10.10
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment: 
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-harvash2004@yahoo.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      titanicnet:
        ipv4_address: 10.10.10.20
    restart: unless-stopped

networks:
  titanicnet:
    external: true    

volumes:
  pgdata:
  pglogs:
  pgadmin:

