version: '3.5'

services:
  postgres:
    container_name: db_postgres
    build: 
      context: .
      dockerfile: ../Dockerfile
    image: pgtitanic
    command: >
      postgres -c logging_collector=on 
      -c log_destination=stderr 
      -c log_directory=/pgdb/logs 
      -c log_filename=postgresql.log 
      -c log_file_mode=0600 
      -c log_truncate_on_rotation=on 
      -c log_rotation_age=1d 
      -c log_rotation_size=10MB  
      -c shared_preload_libraries='pg_stat_statements'
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /pgdb/data
      POSTGRES_DB: titanicdb
    volumes:
      - pgdata:/pgdb
      - ./provision/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment: 
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-harvash2004@yahoo.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - pgadmin:/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  pgdata:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /Users/cxa791/TitanicLost/assets/pgdb
  pgadmin:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /Users/cxa791/TitanicLost/assets/pgadmin
